import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Domenico Gagliardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>Domenico Gagliardo - Portfolio Ingegnere Informatico</title>
        <meta name="title" content="Domenico Gagliardo - Portfolio Ingegnere Informatico"/>
        <meta content="Benvenuto nel mio sito web portfolio. Sono Domenico Gagliardo, un Ingegnere Informatico. Scopri di più su di me." name="description" />
        <meta content="ingegneria informatica, programmazione, portfolio, github, unisa, università di salerno, politecnico di torino, software engineer, software developer, mobile developer, full-stack developer" name="keywords"/>
        <meta name="robots" content="index, follow"/>
        <meta name="revisit-after" content="30 days"/>
        <meta name="author" content="Domenico Gagliardo"/>
        <meta name="copyright" content="Domenico Gagliardo"/>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
